let Promise = require('./p_09');

// let p = new Promise((resolve, reject) => {
//     reject('err');
// });
// p.then().then().catch(r=>{
//     // catch是then的第二个方法，默认return undefined
//     console.log(r);
// }).then(data=>{
//     console.log(data);
// });

// Promise.reject('hello').catch(err => {
//     console.log(err);
// });